spring:
  config:
    activate:
      on-profile: dev


  ai:
    ollama:
      base-url: http://172.19.55.232:11434
      embedding:
        model: embeddinggemma:300m



  # Redis 配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:myRedisPass123}
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fitness_ai_db
    username: fitness_user
    password: myPostgresPass123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    encoding: UTF-8


logging:
  level:
    com.fitness: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG
    org.springframework.ai: DEBUG
    com.alibaba.cloud.ai: DEBUG
    org.springframework.ai.chat: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50}:%line - %msg%n"


